spring:
  datasource:
    username: sa
    password: sa
    schema: classpath:schema-hsql.sql
    data: classpath:data-hsql.sql
    url: jdbc:hsqldb:mem:hsql_db
  output:
    ansi:
      enabled: always
#  aop:
#    proxy-target-class: false

logging:
  level:
    org.springframework.jdbc: trace
    org.springframework: debug
