spring:
  mail:
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    host: smtp.139.com
# todo:: 在这里指定账号密码
    username:
    password:
