spring:
  profiles: def

debug: true
---
spring:
  profiles: color
  output:
    ansi:
      enabled: always
---
spring:
  profiles: file
logging:
  file: logging_sample.log
---
spring:
  profiles: level
logging:
  level:
    java.lang.String: info
    java.lang.Integer: warn
---
spring:
  profiles: custom
  output:
    ansi:
      enabled: always
logging:
  config: classpath:custom-logback-spring.xml
  file: custom_logging_sample

