spring:
  profiles: def
debug: true
---
spring:
  profiles: color
  output:
    ansi:
      enabled: always
---
spring:
  profiles: file
logging:
  file: logging_sample.log
---
spring:
  profiles: level
logging:
  level:
    java.lang.String: info
    java.lang.Integer: warn
---
spring:
  profiles: format
logging:
  pattern:
    console: -[%clr(${LOG_LEVEL_PATTERN:-%5p})]  %m%n}
---
spring:
  profiles: custom
logging:
  config: classpath:custom-logback-spring.xml
---
spring:
  profiles: extensions
logging:
  config: classpath:extension-logback-spring.xml
author:
  name: ^_^
