spring:
  profiles: def

debug: true
---
spring:
  profiles: color
  output:
    ansi:
      enabled: always
---
spring:
  profiles: file
logging:
  file: logging_sample.log
---
spring:
  profiles: level
logging:
  level:
    java.lang.String: info
    java.lang.Integer: warn
